"""
GitHub integration — creates a new repo and pushes generated project files.
Uses the GitHub REST API (no git binary required).
"""

import base64
import re
import requests
from typing import Dict, List, Tuple

import config

BASE = "https://api.github.com"


def _headers():
    return {
        "Authorization": f"token {config.GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "ai-web-team/1.0",
    }


def create_repo(repo_name: str, description: str = "", private: bool = False) -> Dict:
    """Create a new GitHub repo. Returns repo info dict."""
    payload = {
        "name":        repo_name,
        "description": description,
        "private":     private,
        "auto_init":   False,
    }
    r = requests.post(f"{BASE}/user/repos", json=payload, headers=_headers(), timeout=15)
    r.raise_for_status()
    return r.json()


def push_file(owner: str, repo: str, path: str, content: str, message: str = "feat: initial commit") -> bool:
    """Create or update a single file in the repo via the Contents API."""
    encoded = base64.b64encode(content.encode()).decode()
    payload = {"message": message, "content": encoded}

    # Check if file already exists (to get sha for update)
    check = requests.get(f"{BASE}/repos/{owner}/{repo}/contents/{path}", headers=_headers(), timeout=10)
    if check.status_code == 200:
        payload["sha"] = check.json().get("sha")

    r = requests.put(
        f"{BASE}/repos/{owner}/{repo}/contents/{path}",
        json=payload,
        headers=_headers(),
        timeout=15,
    )
    return r.status_code in (200, 201)


def parse_developer_output(output: str) -> List[Tuple[str, str]]:
    """
    Parse the Developer agent's output and extract (filepath, code) pairs.
    Looks for patterns like:
      ### `path/to/file.ext`
      ```lang
      code
      ```
    """
    files = []
    # Match ### `filepath` followed by a code block
    pattern = re.compile(
        r'###\s+`([^`]+)`\s*\n```[^\n]*\n(.*?)```',
        re.DOTALL
    )
    for match in pattern.finditer(output):
        filepath = match.group(1).strip()
        code     = match.group(2)
        files.append((filepath, code))

    # Fallback: also catch #### or ## headings with code blocks
    if not files:
        pattern2 = re.compile(
            r'(?:#{1,4})\s+[`"]?([^\n`"]+\.\w+)[`"]?\s*\n```[^\n]*\n(.*?)```',
            re.DOTALL
        )
        for match in pattern2.finditer(output):
            filepath = match.group(1).strip()
            code     = match.group(2)
            files.append((filepath, code))

    return files


def push_project(project_id: str, repo_name: str, brief: str) -> str:
    """
    Full push: create repo + push all artifacts.
    Returns the GitHub repo URL.
    """
    import database as db

    owner = config.GITHUB_USERNAME
    artifacts = db.get_artifacts(project_id)

    # Create repo
    repo_info = create_repo(
        repo_name=repo_name,
        description=f"Generated by ai-web-team — {brief[:100]}",
        private=False,
    )
    html_url = repo_info.get("html_url", "")

    # Push PM, Designer, Architect outputs as docs
    label_map = {
        "pm":        "docs/PRD.md",
        "designer":  "docs/DESIGN.md",
        "architect": "docs/ARCHITECTURE.md",
    }
    for artifact in artifacts:
        agent    = artifact["agent"]
        content  = artifact["content"]

        if agent in label_map:
            push_file(owner, repo_name, label_map[agent], content, f"docs: add {agent} output")

        elif agent == "developer":
            # Parse and push individual code files
            files = parse_developer_output(content)
            if files:
                for filepath, code in files:
                    # Sanitize path
                    filepath = filepath.lstrip("/").replace("..", "")
                    push_file(owner, repo_name, filepath, code, "feat: initial implementation")
            else:
                # Fallback: push raw developer output
                push_file(owner, repo_name, "developer_output.md", content, "feat: developer output")

    db.update_project(project_id, github_url=html_url)
    return html_url
